"""
Abstract Base Class for Provider-Independent LLM Architecture.
"""

from abc import ABC, abstractmethod
from typing import List, Optional
from pydantic import BaseModel, Field


class LLMResponse(BaseModel):
    """Structured response container for LLM completions."""
    content: str = Field(..., description="Raw text generated by LLM.")
    model: str = Field(..., description="Model identifier used for generation.")
    provider: str = Field(default="", description="Provider identifier used for generation.")
    prompt_tokens: int = Field(default=0, description="Input prompt token count.")
    completion_tokens: int = Field(default=0, description="Output completion token count.")


class LLMProvider(ABC):
    """Abstract contract required for all LLM Provider implementations.
    
    Required Capabilities:
    - provider_name()
    - available_models()
    - generate()
    - health_check()
    """

    @abstractmethod
    def provider_name(self) -> str:
        """Return the friendly identifier string of the LLM backend provider."""
        pass

    @abstractmethod
    def available_models(self) -> List[str]:
        """Return list of available model identifiers supported by the provider."""
        pass

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        """Synchronously send a completion prompt to the LLM backend.

        Args:
            prompt: User or contextual prompt text.
            system_prompt: Optional system instruction prompt.
            model: Model identifier override.
            temperature: Sampling temperature override.
            max_tokens: Maximum tokens override.

        Returns:
            Completion text output.
        """
        pass

    @abstractmethod
    def health_check(self) -> bool:
        """Perform API connectivity and authentication health check."""
        pass

    async def generate_async(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        """Asynchronously send a completion prompt to the LLM backend."""
        # Default async implementation falls back to synchronous generate
        return self.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
        )

    async def health_check_async(self) -> bool:
        """Asynchronously perform API connectivity health check."""
        return self.health_check()

    async def complete(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> str:
        """Backward compatible async completion method matching ILLMProvider contract."""
        return await self.generate_async(
            prompt=prompt,
            system_prompt=system_prompt,
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
        )
