"""
OpenRouter API Client for LLM completions.

Reads API key from OPENROUTER_API_KEY environment variable or AppConfig YAML settings.
Allows dynamic model selection with configurable defaults (e.g., nvidia/nemotron-3-ultra-550b-a55b:free).
"""

import os
import httpx
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field

from core.config import load_config, AppConfig
from core.logger import get_logger

logger = get_logger("llm_client")


class LLMResponse(BaseModel):
    """Structured response container for LLM completions."""
    content: str = Field(..., description="Raw text generated by LLM.")
    model: str = Field(..., description="Model used for generation.")
    prompt_tokens: int = Field(default=0, description="Input prompt token count.")
    completion_tokens: int = Field(default=0, description="Output completion token count.")


class OpenRouterClient:
    """Production client for OpenRouter API."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        config: Optional[AppConfig] = None
    ):
        self.config = config or load_config()

        # Priority 1: Direct argument -> Priority 2: Env Var OPENROUTER_API_KEY -> Priority 3: YAML config
        env_key = os.getenv("OPENROUTER_API_KEY")
        if api_key:
            resolved_key = api_key
        elif env_key:
            resolved_key = env_key
        else:
            resolved_key = self.config.openrouter.api_key.get_secret_value()

        self.api_key = resolved_key
        self.model = model or self.config.openrouter.default_model
        self.base_url = self.config.openrouter.base_url.rstrip("/")
        self.timeout = self.config.openrouter.timeout_seconds

        self._headers = {
            "Authorization": f"Bearer {self.api_key}",
            "HTTP-Referer": self.config.openrouter.site_url,
            "X-Title": self.config.openrouter.app_name,
            "Content-Type": "application/json",
        }

    def complete(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model_override: Optional[str] = None,
        temperature: float = 0.2,
        max_tokens: int = 2048,
    ) -> LLMResponse:
        """Synchronously send completion request to OpenRouter API."""
        selected_model = model_override or self.model
        url = f"{self.base_url}/chat/completions"

        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload: Dict[str, Any] = {
            "model": selected_model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        logger.debug(f"Sending LLM request to OpenRouter (Model: {selected_model})")

        with httpx.Client(timeout=self.timeout) as client:
            try:
                response = client.post(url, headers=self._headers, json=payload)
                if response.status_code != 200:
                    logger.warning(f"OpenRouter API primary model failure ({response.status_code}): {response.text}")
                    # Fallback to secondary model if primary failed
                    if selected_model != self.config.openrouter.fallback_model:
                        fallback = self.config.openrouter.fallback_model
                        logger.info(f"Retrying completion with fallback model: {fallback}")
                        payload["model"] = fallback
                        response = client.post(url, headers=self._headers, json=payload)

                response.raise_for_status()
                data = response.json()

                choices = data.get("choices", [])
                content = choices[0].get("message", {}).get("content", "") if choices else ""
                usage = data.get("usage", {})

                return LLMResponse(
                    content=content,
                    model=data.get("model", selected_model),
                    prompt_tokens=usage.get("prompt_tokens", 0),
                    completion_tokens=usage.get("completion_tokens", 0)
                )

            except Exception as e:
                logger.error(f"OpenRouter API request failed: {str(e)}")
                raise RuntimeError(f"OpenRouter API request error: {str(e)}") from e

    async def complete_async(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model_override: Optional[str] = None,
        temperature: float = 0.2,
        max_tokens: int = 2048,
    ) -> LLMResponse:
        """Asynchronously send completion request to OpenRouter API."""
        selected_model = model_override or self.model
        url = f"{self.base_url}/chat/completions"

        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload: Dict[str, Any] = {
            "model": selected_model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.post(url, headers=self._headers, json=payload)
                response.raise_for_status()
                data = response.json()

                choices = data.get("choices", [])
                content = choices[0].get("message", {}).get("content", "") if choices else ""
                usage = data.get("usage", {})

                return LLMResponse(
                    content=content,
                    model=data.get("model", selected_model),
                    prompt_tokens=usage.get("prompt_tokens", 0),
                    completion_tokens=usage.get("completion_tokens", 0)
                )
            except Exception as e:
                logger.error(f"Async OpenRouter API request failed: {str(e)}")
                raise RuntimeError(f"Async OpenRouter API request error: {str(e)}") from e
