"""
Pydantic Data Models for Extensible Security-Tool Adapter Subsystem.
"""

from datetime import datetime, timezone
from typing import Dict, List, Any, Optional
from pydantic import BaseModel, Field


class ToolCapabilityMetadata(BaseModel):
    """Capability description model for a security tool adapter."""
    supports_api: bool = Field(default=False, description="Tool communicates via REST/RPC API.")
    supports_async: bool = Field(default=True, description="Tool supports asynchronous execution.")
    supports_auth: bool = Field(default=True, description="Tool requires target authorization acknowledgement.")
    categories: List[str] = Field(default_factory=list, description="Tool assessment categories.")
    supported_options: Dict[str, str] = Field(default_factory=dict, description="Allowed configuration options and types.")


class NormalizedFinding(BaseModel):
    """Canonical schema for normalized security findings produced across tool adapters."""
    finding_id: str = Field(..., description="Unique finding identifier.")
    category: str = Field(..., description="Finding category (e.g. open_port, web_vuln, packet_anomaly).")
    title: str = Field(..., description="Short summary title.")
    severity: str = Field(default="info", description="Severity level (info, low, medium, high, critical).")
    details: Dict[str, Any] = Field(default_factory=dict, description="Detailed finding attributes.")
    evidence: str = Field(default="", description="Raw evidence string or proof.")


class NormalizedToolEvidence(BaseModel):
    """Normalized evidence output container generated by tool adapters."""
    tool_name: str = Field(..., description="Name of the security tool adapter.")
    tool_version: str = Field(default="unknown", description="Detected tool version.")
    target: str = Field(..., description="Target evaluated.")
    execution_time_ms: float = Field(..., description="Wall-clock duration in milliseconds.")
    success: bool = Field(..., description="Execution success flag.")
    status_code: int = Field(default=0, description="Return status code (0 for success).")
    raw_output: Any = Field(default="", description="Raw command stdout or API JSON response.")
    normalized_findings: List[NormalizedFinding] = Field(default_factory=list, description="Canonical normalized findings.")
    errors: List[str] = Field(default_factory=list, description="Captured execution error messages.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Execution metrics and environment details.")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC timestamp."
    )
